version: 0.2
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: ""  
        LoadBalancerInfo:
          ContainerName: "fitfuel"
          ContainerPort: 
