version: 0.2

env:
  variables:
    REPOSITORY_URI: "314146300525.dkr.ecr.us-east-1.amazonaws.com/fitfuel"
  compute-type: BUILD_GENERAL1_MEDIUM
  image: "aws/codebuild/standard:5.0"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - apt-get update && apt-get install -y sqlite3

  pre_build:
    commands:
      - set -e
      - echo "Logging in to AWS ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - IMAGE_TAG=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest} | cut -c 1-7)

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo "[{\"name\":\"fitfuel\",\"imageUri\":\"$REPOSITORY_URI:$IMAGE_TAG\"}]" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
